version: '3.4'
services:
  mysql:
    image: mysql:8
    restart: always
    container_name: mysql-8
    environment:
      MYSQL_ROOT_PASSWORD: 'S3cret'
    ports:
      - 3306:3306
    networks:
      - dockernet

networks:
  dockernet: